ICETool cleanup. All additional scripts are merged into icetool

diff --git a/system/bin/icetool b/system/bin/icetool
--- a/system/bin/icetool
+++ b/system/bin/icetool
@@ -6,40 +6,16 @@
 # plus a configuration interface that allows modifying ICETool.apk
 # interface (adding and removing tabs and options)
 #
-
-ICETOOL_VERSION="0.87" # Script version
+# TODO:
+#
+# * UV scripts should look for configs on an sdcard folder
+# * There are still some commands harcoded into the app
+#   (labeled with *). It's needed to make them optional too
+#   and exported via icetool setup
+#
+. /system/etc/icetool.conf
+ICETOOL_VERSION="0.88" # Script version
 HELP="Usage: $0 <cmd> ..."
-BASE_DIR=/sdcard/blackice
-MARKET_DIR=$BASE_DIR/market
-RIL_DIR=$BASE_DIR/ril
-GPS_DIR=$BASE_DIR/gpsconf
-BOOTANIM_DIR=$BASE_DIR/bootanimation/
-BASE_URL=http://blackice.omca.co.uk/download/buildpackages/
-ICETOOL_URL=$BASE_URL/icetool.tgz
-ICETOOL_VERSION_URL=$BASE_URL/icetool.version
-ICETOOL_AUTORUN=$BASE_DIR/autorun.txt
-RECOVERY_CMD_WHITELIST="market gpsconf ril density braviaengine bootanim extrapkg bootsoundoff overlay"
-
-### More extra content to come
-EXTRA_APKS="org.zeam-1.apk:366e89a3a8ef8e6075b3b5bde593ae82 \
-            ADWLauncher.apk:366e89a3a8ef8e6075b3b5bde593ae82 \
-            ICS_2.4_Launcher_2.apk:e518049b4359ffcd4769a98b034f73bf \
-            Google+Music+4.0.1.apk:d31a972968ab0798921aa6f3b9b4aaf1 \
-"
-# Extra packages that are supposed to be installed on system
-EXTRA_APKS_SYS="ADWLauncher.apk"
-
-# Extra APKs
-EXTRA_APKS_NAMES=`for i in $EXTRA_APKS; do B=${i%\:*} ; echo "$B@" ; done | tr '\n' ' ' | sed 's/\ *//g'`
-EXTRA_APKS_DESCR="Zeam Launcher@ADW Launcher@ICS v2.4 Launcher2@Google Music v4.0.1"
-
-# Extra TGZ on /system
-# FIXME - allow any tgz
-EXTRA_PKGS="nexussswype.tgz:cf933c0e76022bfc16d9e00df9a0c3d0 \
-            htcime.tgz:4f46cc059c890db70b324816e8722775"
-EXTRA_PKG_NAMES=`for i in $EXTRA_PKGS; do B=${i%\:*} ; echo "$B@" ; done | tr '\n' ' ' | sed 's/\ *//g'`
-EXTRA_PKG_DESCR="Nexus S Swype (black)@HTC IME Mod (grey)"
-
 ### Only root allowed
 WHO=`whoami`
 if [ "$WHO" != "root" ]; then
@@ -57,111 +33,36 @@ die () {
   exit 1
 }
 
-####
-# Here we setup the offered commands for the gui
-# We will print the following tags:
-# CATEGORIES: high level categories (=gui tabs)
-# CATEGORY_COMMANDS: relation of commands included in each high level category
-# COMMANDS:   all the supported commands
-# OPTIONS:    options available for each command (if any)
-Setup() {
-  # Categories
-  CATEGORIES="CATEGORIES:sys@apps@dsp@gps@ril"
+###
+# AutoInstall
+# Execute a sequence of commands available on a fixed path
+# configuration file
+AutoInstall() {
 
-  # Categories - commands relationship
-  CATEGORY_COMMANDS="${CATEGORY_COMMANDS}CATEGORY_COMMANDS:sys:upgrade@remount@fastcharge@charge@hosts@density@braviaengine\n"
-  CATEGORY_COMMANDS="${CATEGORY_COMMANDS}CATEGORY_COMMANDS:apps:market@bootanim@extrapkg@extraapk\n"
-  CATEGORY_COMMANDS="${CATEGORY_COMMANDS}CATEGORY_COMMANDS:gps:gpsconf\n"
-  CATEGORY_COMMANDS="${CATEGORY_COMMANDS}CATEGORY_COMMANDS:dsp:dspinit\n"
-  CATEGORY_COMMANDS="${CATEGORY_COMMANDS}CATEGORY_COMMANDS:ril:ril\n"
+  # Some considerations from here:
+  # * We are running in a recovery
+  # * We haven't internet connection
+  # * We don't want to reboot (ie: dpi command normally does)
+  export RECOVERY_MODE="1"
+  export PATH=$PATH:/system/bin/:/system/xbin/
 
-  # Basic commands
-  SUPPORTED_COMMANDS="COMMANDS:"
-
-  # Upgrade command
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}upgrade@";
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:upgrade:version@checkversion@icetool\n"; # TODO @rom@kernel
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:upgrade:Show version info@Check for new version@Upgrade ICETool\n"
-
-  # Remount command
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}remount@";
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:remount:rw@ro\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:remount:Remount /system as read/write@Remount /system as read-only\n"
-
-  # hosts command
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}hosts@";
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:hosts:\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:hosts:Refresh hosts file (adfree replacement)\n"
-
-  # Density is mandatory but has 3 options
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}density@";
-  DENSITY_LIST="190@200@240"
-  DENSITY_DESCR="Set LCD density as 190 (LordClockan style)@Set LCD density as 200 (AlienMind style)@Set LCD density as 240 (Default style)"
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:density:$DENSITY_LIST\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:density:$DENSITY_DESCR\n"
-
-  # BraviaEngine has 2 options
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}braviaengine@";
-  BRAVIA_LIST="on@off"
-  BRAVIA_DESCR="Enable Bravia Engine (reboot needed)@Disable Bravia Engine (reboot needed)"
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:braviaengine:$BRAVIA_LIST\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:braviaengine:$BRAVIA_DESCR\n"
-
-  # Boot animations catalog
-  EXTRA_BOOTANIM_NAMES=`ls $BOOTANIM_DIR/ | tr '\n' '@'`
-  EXTRA_BOOTANIM_DESCR=`for i in $BOOTANIM_DIR/*; do basename $i .zip ; done | tr '\n' ' ' | tr ' ' '@' | tr '-' ' '`
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}bootanim@";
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:bootanim:$EXTRA_BOOTANIM_NAMES\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:bootanim:$EXTRA_BOOTANIM_DESCR\n"
-
-  # Rest of market options
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}extraapk@";
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:extraapk:$EXTRA_APKS_NAMES\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:extraapk:$EXTRA_APKS_DESCR\n"
-  SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}extrapkg@";
-  COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:extrapkg:$EXTRA_PKG_NAMES\n";
-  COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:extrapkg:$EXTRA_PKG_DESCR\n"
-
-  # The rest of the commands are optional and depending on environmental factors
-  if [ -f /sys/class/power_supply/battery/force_high_power_charging ]; then
-    SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}fastcharge@"
-    COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:fastcharge:1@0\n"
-    COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:fastcharge:Force high power charging@Disable high power charging\n"
-  fi
-  if [ -f /sys/devices/platform/rs30100001:00000000/power_supply/battery/charge_on_plug_enabled ]; then
-    SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}charge@"
-    COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:charge:1@0\n"
-    COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:charge:Enable USB charging@Disable USB charging\n"
-  fi
-  if [ -d $MARKET_DIR ]; then
-    SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}market@"
-    MARKET_LIST=`for i in $MARKET_DIR/Vending*.apk; do basename $i ; done | sed 's/Vending-//g' | sed 's/.apk//g' | tr '\n' '@'`
-    MARKET_DESCR=`for i in $MARKET_DIR/Vending*.apk; do basename $i ; done | sed 's/Vending-/Install and launch Market v/g' | sed 's/.apk//g' | tr '\n' '@' `
-    COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:market:$MARKET_LIST\n"
-    COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:market:$MARKET_DESCR\n"
-  fi
-  if [ -d $RIL_DIR ]; then
-    SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}ril@"
-    RIL_LIST=`ls $RIL_DIR/ | tr '\n' '@'`
-    RIL_DESCR=$RIL_LIST
-    COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:ril:showril@$RIL_LIST\n"
-    COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:ril:Show RIL info@$RIL_DESCR\n"
-  fi
-  if [ -d $GPS_DIR ]; then
-    SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}gpsconf@"
-    GPS_LIST=`ls $GPS_DIR/ | tr '\n' '@'`
-    GPS_DESCR=$GPS_LIST
-    COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:gpsconf:$GPS_LIST\n"
-    COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:gpsconf:$GPS_DESCR\n"
-  fi
-  if [ -f /system/bin/snd3254 ]; then
-    SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}dspinit@"
-    DSP_LIST=`echo "" | snd3254 -dspmode | grep -v Please | awk -F'.' '{ printf("%s@",$1); }'`
-    DSP_DESCR=`echo "" | snd3254 -dspmode | grep -v Please | awk '{ printf("%s@",$2); }'`
-    COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:dspinit:$DSP_LIST\n"
-    COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:dspinit:$DSP_DESCR\n"
+  if [ -f "$ICETOOL_AUTORUN" ]; then
+    echo "$ICETOOL_AUTORUN found! applying custom settings..."
+    # Leave the set -x for this execution
+    # This is intended to run from updater-script
+    # and we want verbosity for each option applied
+    cat $ICETOOL_AUTORUN | while read A; do
+      COMMENT=`echo $A | grep -v ^\#`
+      if [ "$COMMENT" = "" ]; then
+        continue
+      fi
+      main $A
+    done
+  else
+    echo "$ICETOOL_AUTORUN not found, leaving default settings..."
   fi
 }
+
 
 ListCommands() {
   printf "ICETOOL_VERSION:$ICETOOL_VERSION\n"
@@ -189,7 +90,7 @@ CheckVersion() {
   mkdir -p /data/tmp
   cd /data/tmp
   rm -f icetool.version
-  wget "$ICETOOL_VERSION_URL" &>/dev/null
+  wget "$ICETOOL_VERSION_URL"  >/dev/null 2>&1
   RET=$?
   if [ "$RET" != "0" ]; then
     echo "Error checking new version"
@@ -554,19 +455,6 @@ TestBootAnim() {
 
 ###
 #
-# BootSoundOff - Disable default bootsound
-BootSoundOff() {
-  RemountSys "rw"
-  mkdir -p /data/local/boot/
-  if [ -e /system/media/android_audio.mp3 ]; then
-    mv /system/media/android_audio.mp3 /data/local/boot/android_audio.mp3
-  fi
-  RemountSys "ro"
-  echo "Boot sound disabled"
-}
-
-###
-#
 # Overlay - Copy custom content from sdcard
 Overlay() {
   local DST="$1"
@@ -589,37 +477,174 @@ Overlay() {
   umount $DST
 }
 
-
-
 ###
-# AutoInstall
-# Execute a sequence of commands available on a fixed path
-# configuration file
-AutoInstall() {
+# UV
+UV() {
+  local script=$1
+  if [ ! -f "$script" ]; then
+    echo "Not found UV script: $script"
+    exit 1
+  fi
+  mount -o remount,rw /system
+  rm -f /system/etc/init.d/99voltages
+  cp $script /system/etc/init.d/99voltages
+  chmod 777 /system/etc/init.d/99voltages
+  /system/etc/init.d/99voltages
+  mount -o remount,ro /system
+  echo "UV script $script applied"
+} 
 
-  # Some considerations from here:
-  # * We are running in a recovery
-  # * We haven't internet connection
-  # * We don't want to reboot (ie: dpi command normally does)
-  export RECOVERY_MODE="1"
-  export PATH=$PATH:/system/bin/:/system/xbin/
-
-  if [ -f "$ICETOOL_AUTORUN" ]; then
-    echo "$ICETOOL_AUTORUN found! applying custom settings..."
-    # Leave the set -x for this execution
-    # This is intended to run from updater-script
-    # and we want verbosity for each option applied
-    cat $ICETOOL_AUTORUN | while read A; do
-      COMMENT=`echo $A | grep -v ^\#`
-      if [ "$COMMENT" = "" ]; then
-        continue
-      fi
-      main $A
-    done
-  else
-    echo "$ICETOOL_AUTORUN not found, leaving default settings..."
+BootSound() {
+  bprop=/system/build.prop
+  play=$(cat $bprop | egrep -c -i -o ro.config.play.bootsound=1)
+  if [ "$play" = "1" ]; then
+    stagefright -a -o /system/media/android_audio.mp3
   fi
 }
+
+###
+#
+# BootSoundOn - Enable default bootsound
+BootSoundOn() {
+  mount -o remount,rw /system
+  if [ -e /data/local/boot/android_audio.mp3 ];
+  	then
+  		cp /data/local/boot/android_audio.mp3 /system/media/android_audio.mp3
+  		rm /data/local/boot/android_audio.mp3
+  fi
+  sleep 1
+  mount -o remount,ro /system
+  echo "boot sound enabled.."
+}
+
+###
+#
+# BootSoundOff - Disable default bootsound
+BootSoundOff() {
+  RemountSys "rw"
+  mkdir -p /data/local/boot/
+  if [ -e /system/media/android_audio.mp3 ]; then
+    mv /system/media/android_audio.mp3 /data/local/boot/android_audio.mp3
+  fi
+  RemountSys "ro"
+  echo "Boot sound disabled"
+}
+
+###
+#
+# BootSoundEnable - Enable boot sound service at boottime
+BootSoundEnable() {
+  echo "preparing system..."
+  #Setting up the system for read/write access
+  mount -o remount,rw /system
+  #linking busybox mkdir (broken in rc2)
+  rm /system/bin/mkdir
+  ln -s /system/xbin/mkdir /system/bin/mkdir
+  mkdir -p /data/local/boot
+  echo "checking for previous bootsound installation..."
+  if [ -e /system/bin/bootsound ];
+  	then
+  		echo "bootsound already enabled, exiting.."
+  		mount -o remount,ro /system
+  		exit
+  fi
+  if [ "`ls /sbin|grep -q recovery;echo $?`" = "0" ];
+  then
+      mount -a > /dev/null
+      recoverymode=y
+  else
+      mount -o rw,remount /system
+      recoverymode=n
+  fi
+  echo "preparing startup scripts..."
+  #This is to create the needed scripts in init.local.rc
+  echo '' >> /system/etc/init.local.rc
+  echo '' >> /system/etc/init.local.rc
+  echo '###Bootsound - Safe to Delete: Start ###' >> /system/etc/init.local.rc
+  echo "" >> /system/etc/init.local.rc
+  echo 'service bootsound /system/bin/bootsound' >> /system/etc/init.local.rc
+  echo '        user media' >> /system/etc/init.local.rc
+  echo '        group audio' >> /system/etc/init.local.rc
+  echo '        disabled' >> /system/etc/init.local.rc
+  echo '        oneshot' >> /system/etc/init.local.rc
+  echo '' >> /system/etc/init.local.rc
+  echo 'on property:init.svc.bootanim=running   # to correct timin' >> /system/etc/init.local.rc
+  echo '        start bootsound' >> /system/etc/init.local.rc
+  echo '' >> /system/etc/init.local.rc
+  echo 'on property:dev.bootcomplete=1' >> /system/etc/init.local.rc
+  echo '        stop bootsound' >> /system/etc/init.local.rc
+  echo '### Bootsound - Safe to Delete: End ###' >> /system/etc/init.local.rc
+  echo "creating script for bootsound in /system/bin..."
+  #Now creating the bootsound script
+  touch /system/bin/bootsound
+  echo '#!/system/bin/sh' >> /system/bin/bootsound
+  echo '' >> /system/bin/bootsound
+  echo 'bprop=/system/build.prop' >> /system/bin/bootsound
+  echo '' >> /system/bin/bootsound
+  echo 'play=$(cat $bprop | egrep -c -i -o ro.config.play.bootsound=1)' >> /system/bin/bootsound
+  echo 'if [ "$play" = "1" ]; then' >> /system/bin/bootsound
+  echo '        stagefright -a -o /system/media/android_audio.mp3' >> /system/bin/bootsound
+  echo 'fi' >> /system/bin/bootsound
+  echo 'exit 0' >> /system/bin/bootsound
+  
+  #Changing some permissions
+  chmod 777 /system/bin/bootsound
+  chown root:shell /system/bin/bootsound
+  echo '' >> /system/build.pro
+  echo 'ro.config.play.bootsound=1' >> /system/build.prop
+  #removed self-destruct, script checks for previous install
+  sleep 1
+  mount -o ro,remount /system
+  echo "done."
+}
+
+###
+#
+#
+NewBootAnim() {
+  mount -o remount,rw /system
+  if [ -e /sdcard/bootanimation.zip ];
+  	then
+  		cp /sdcard/bootanimation.zip /system/media/bootanimation.zip
+  fi
+  sleep 1
+  mount -o remount,ro /system
+  echo "new boot anim set."
+}
+
+##
+#
+#
+NewBootSound() {
+  mount -o remount,rw /system
+  if [ -e /sdcard/android_audio.mp3 ];
+  	then
+  		cp /sdcard/android_audio.mp3 /system/media/android_audio.mp3
+  fi
+  sleep 1
+  mount -o remount,ro /system
+  echo "new boot sound set."
+  sleep 2
+  bootsound
+}
+
+###
+#
+#
+NewLockSounds() {
+  mount -o remount,rw /system >/dev/null 2>&1
+  if [ -e /sdcard/lock.ogg ]; then
+    cp /sdcard/lock.ogg /system/media/audio/ui/Lock.ogg
+    echo "New lock sound set"
+  fi
+  if [ -e /sdcard/unlock.ogg ]; then
+    cp /sdcard/unlock.ogg /system/media/audio/ui/Unlock.ogg
+    echo "New unlock sound set"
+  fi
+  sleep 1
+  mount -o remount,ro /system >/dev/null 2>&1
+}
+
 
 ###
 # Cleanup - for older version directories, etc
@@ -651,26 +676,54 @@ main() {
 
   #### All of supported commands
   case $CMD in
+
+    # Autoconfiguration of the tool
     "setup")        Setup ; ListCommands ;;
     "autoinstall")  AutoInstall ;;
     "upgrade")      Upgrade    "$1" ;;
+
+    # Autorun.txt commands
+    "overlay")      Overlay    "$1" "$2" ;;
+    "cleanup")      Cleanup    "$1" ;;
+
+    # Kernel tweaks
     "fastcharge")   FastCharge "$1" ;;
     "charge")       Charge     "$1" ;;
     "remount")      Remount    "$1" ;;
+    "extraapk")     ExtraAPK   "$1" ;;
+    "extrapkg")     ExtraPKG   "$1" ;;
+
+    # Sound management
+    "dspinit")       DSPInit    "$1" ;;
+    "bootsound")     BootSound       ;;   # * Hardcoded into ICETool.apk
+    "bootsoundon")   BootSoundOn     ;;   # *
+    "bootsoundoff")  BootSoundOff    ;;   # *
+    "newbootsound")  NewBootSound    ;;   # *
+    "newlocksounds") NewLockSounds   ;;   # *
+
+    # Boot animation management
+    "bootanim")     BootAnim   "$1" ;;    # *
+    "testbootanim") TestBootAnim    ;;    # *
+    "newbootanim")  NewBootAnim     ;;    # *
+
+    # Other customizations
     "hosts")        InstallHost     ;;
     "market")       Market     "$1" ;;
     "gpsconf")      GPSConf    "$@" ;;
-    "dspinit")      DSPInit    "$1" ;;
     "ril")          RIL        "$1" ;;
     "density")      Density    "$1" ;;
     "braviaengine") BraviaEngine "$1" ;;
-    "extraapk")     ExtraAPK   "$1" ;;
-    "extrapkg")     ExtraPKG   "$1" ;;
-    "bootanim")     BootAnim   "$1" ;;
-    "testbootanim") TestBootAnim    ;;
-    "bootsoundoff") BootSoundOff    ;;
-    "overlay")      Overlay    "$1" "$2" ;;
-    "cleanup")      Cleanup    "$1" ;;
+
+    # Old independent scripts
+    # To be renamed in ICETool.apk
+
+    # UV Scripts
+    "25uvon")       UV "/system/media/uvscripts/25uv/99voltages"  ;;     # *
+    "50uvon")       UV "/system/media/uvscripts/50uv/99voltages"  ;;     # *
+    "puvon")        UV "/system/media/uvscripts/puv/99voltages"   ;;     # *
+    "puvxon")       UV "/system/media/uvscripts/puvx/99voltages"  ;;     # *
+    "uuvon")        UV "/system/media/uvscripts/uuv/99voltages"   ;;     # *
+    "uvoff")        UV "/system/media/uvscripts/stock/99voltages" ;;     # *
   
     ### Any other command - we are a wrapper
     *)            exec $CMD $@ ;;
