Autorun scripts for updater-scripts

diff --git a/system/bin/icetool b/system/bin/icetool
--- a/system/bin/icetool
+++ b/system/bin/icetool
@@ -1,5 +1,15 @@
 #!/system/xbin/bash
-ICETOOL_VERSION="0.7" # Script version
+#
+# icetool - by AlienMind
+# ICETool.apk companion scripts
+# It provides an execution interface for controlled commands,
+# plus a configuration interface that allows modifying ICETool.apk
+# interface (adding and removing tabs and options)
+#
+# TODO - merge switchkeyboard and switchlauncher separate scripts
+#
+
+ICETOOL_VERSION="0.81" # Script version
 HELP="Usage: $0 <cmd> ..."
 BASE_DIR=/sdcard/blackice
 MARKET_DIR=$BASE_DIR/market
@@ -9,7 +19,8 @@ BOOTANIM_DIR=$BASE_DIR/bootanimation/
 BASE_URL=http://www.losinj.com/blackice
 ICETOOL_URL=$BASE_URL/icetool.tgz
 ICETOOL_VERSION_URL=$BASE_URL/icetool.version
-WHO=`whoami`
+ICETOOL_AUTORUN=$BASE_DIR/autorun.txt
+RECOVERY_CMD_WHITELIST="market gpsconf ril density bootanim switchlauncher switchkeyboard"
 
 ### More extra content to come
 EXTRA_APKS="ICS_2.4_Launcher_2.apk:e518049b4359ffcd4769a98b034f73bf \
@@ -30,11 +41,8 @@ EXTRA_KEY_DESCR="Nexus S Swype (black)@HTC IME Mod (grey)"
 EXTRA_LAUNCH_NAMES="udlauncher@adwlauncher"
 EXTRA_LAUNCH_DESCR="UD Launcher (black)@ADW Launcher (color)"
 
-die () {
-  echo $@
-  exit 1
-}
-
+### Only root allowed
+WHO=`whoami`
 if [ "$WHO" != "root" ]; then
   echo "Must be root"
   exit 1
@@ -44,8 +52,11 @@ if [ "$1" = "" ]; then
   echo "$HELP"
   exit 2
 fi
-CMD=$1
 
+die () {
+  echo $@
+  exit 1
+}
 
 ####
 # Here we setup the offered commands for the gui
@@ -121,8 +132,8 @@ Setup() {
   fi
   if [ -d $MARKET_DIR ]; then
     SUPPORTED_COMMANDS="${SUPPORTED_COMMANDS}market@"
-    MARKET_LIST=`for i in $MARKET_DIR/Vending*.apk; do basename $i ; done | tr '\n' '@'`
-    MARKET_DESCR=`echo $MARKET_LIST | sed 's/Vending-/Install and launch Market v/g' | sed 's/.apk//g'`
+    MARKET_LIST=`for i in $MARKET_DIR/Vending*.apk; do basename $i ; done | sed 's/Vending-//g' | sed 's/.apk//g' | tr '\n' '@'`
+    MARKET_DESCR=`for i in $MARKET_DIR/Vending*.apk; do basename $i ; done | sed 's/Vending-/Install and launch Market v/g' | sed 's/.apk//g' | tr '\n' '@' `
     COMMAND_OPTIONS="${COMMAND_OPTIONS}OPTIONS:market:$MARKET_LIST\n"
     COMMAND_DESCRIPTIONS="${COMMAND_DESCRIPTIONS}DESCRIPTIONS:market:$MARKET_DESCR\n"
   fi
@@ -212,11 +223,16 @@ UpgradeICETool() {
 
 RemountSys() {
   local MODE=$1
-  mount -o remount,$MODE /system
+  mount -o remount,$MODE /system > /dev/null 2>&1
 }
 
 Reboot() {
   local PAUSE=$1
+
+  if [ "$RECOVERY_MODE" != "" ]; then
+    return 0
+  fi
+
   printf "Syncing...\n"
   sync ; sync ; sync
   printf "Rebooting in $PAUSE seconds...\n"
@@ -236,12 +252,16 @@ InstallMarket() {
   rm -f /data/app/com.android.vending*apk
   cp $APK /system/app/Vending.apk
   chmod 644 /system/app/Vending.apk
-  pm install $APK
+  if [ "$RECOVERY_MODE" != "1" ]; then
+    pm install $APK
+  fi
   RemountSys "ro"
 }
 
 LaunchMarket() {
-  am start -a android.intent.action.MAIN -n com.android.vending/com.android.vending.AssetBrowserActivity
+  if [ "$RECOVERY_MODE" != "1" ]; then
+    am start -a android.intent.action.MAIN -n com.android.vending/com.android.vending.AssetBrowserActivity
+  fi
 }
 
 Market() {
@@ -437,7 +457,34 @@ TestBootAnim() {
   kill $PID
 }
 
+###
+# AutoInstall
+# Execute a sequence of commands available on a fixed path
+# configuration file
+AutoInstall() {
 
+  # Some considerations from here:
+  # * We are running in a recovery
+  # * We haven't internet connection
+  # * We don't want to reboot (ie: dpi command normally does)
+  export RECOVERY_MODE="1"
+
+  if [ -f "$ICETOOL_AUTORUN" ]; then
+    echo "$ICETOOL_AUTORUN found! applying custom settings..."
+    # Leave the set -x for this execution
+    # This is intended to run from updater-script
+    # and we want verbosity for each option applied
+    cat $ICETOOL_AUTORUN | while read A; do
+      COMMENT=`echo $A | grep -v ^\#`
+      if [ "$COMMENT" = "" ]; then
+        continue
+      fi
+      main $A
+    done
+  else
+    echo "$ICETOOL_AUTORUN not found, leaving default settings..."
+  fi
+}
 
 ###
 # Cleanup - for older version directories, etc
@@ -453,27 +500,45 @@ Cleanup() {
   done
 }
 
-#### Supported commands
-shift
-case $CMD in
-  "setup")      Setup ; ListCommands ;;
-  "upgrade")    Upgrade    "$1" ;;
-  "fastcharge") FastCharge "$1" ;;
-  "charge")     Charge     "$1" ;;
-  "remount")    Remount    "$1" ;;
-  "hosts")      InstallHost     ;;
-  "market")     Market     "$1" ;;
-  "gpsconf")    GPSConf    "$@" ;;
-  "dspinit")    DSPInit    "$1" ;;
-  "ril")        RIL        "$1" ;;
-  "density")    Density    "$1" ;;
-  "extraapk")   ExtraAPK   "$1" ;;
-  "bootanim")   BootAnim   "$1" ;;
-  "testbootanim") TestBootAnim  ;;
-  "cleanup")    Cleanup    "$1" ;;
+#### Main execution
+main() {
+  CMD=$1
+  shift
 
-  ### Any other command - we are a wrapper
-  *)            exec $CMD $@ ;;
-esac
+  #### Recovery mode
+  if [ "$RECOVERY_MODE" = "1" ]; then
+    ALLOWED_CMD=`echo $RECOVERY_CMD_WHITELIST | grep $CMD`
+    if [ "$ALLOWED_CMD" = "" ]; then
+      echo "Command $CMD not allowed in recovery mode"
+      exit 1
+    fi
+  fi
 
-exit 0
+  #### All of supported commands
+  case $CMD in
+    "setup")        Setup ; ListCommands ;;
+    "autoinstall")  AutoInstall ;;
+    "upgrade")      Upgrade    "$1" ;;
+    "fastcharge")   FastCharge "$1" ;;
+    "charge")       Charge     "$1" ;;
+    "remount")      Remount    "$1" ;;
+    "hosts")        InstallHost     ;;
+    "market")       Market     "$1" ;;
+    "gpsconf")      GPSConf    "$@" ;;
+    "dspinit")      DSPInit    "$1" ;;
+    "ril")          RIL        "$1" ;;
+    "density")      Density    "$1" ;;
+    "extraapk")     ExtraAPK   "$1" ;;
+    "bootanim")     BootAnim   "$1" ;;
+    "testbootanim") TestBootAnim    ;;
+    "cleanup")      Cleanup    "$1" ;;
+  
+    ### Any other command - we are a wrapper
+    *)            exec $CMD $@ ;;
+    esac
+
+}
+
+## Normal execution - just main
+main $@
+exit $?
